# Generated by Django 4.0.5 on 2022-06-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0002_rename_choice_choice_choice_string_question_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_string',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
