# Generated by Django 4.0.5 on 2022-06-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0003_alter_question_question_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='title',
            field=models.CharField(default='sample test 1', max_length=50),
        ),
    ]
