# Generated by Django 4.0.5 on 2022-06-27 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0004_test_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
