# Generated by Django 4.0.5 on 2022-06-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0005_test_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_assign',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
